/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppElectionYearRouteImport } from './routes/_app/election.$year'
import { Route as AppCompareYear1Year2RouteImport } from './routes/_app/compare.$year1.$year2'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppElectionYearRoute = AppElectionYearRouteImport.update({
  id: '/election/$year',
  path: '/election/$year',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareYear1Year2Route = AppCompareYear1Year2RouteImport.update({
  id: '/compare/$year1/$year2',
  path: '/compare/$year1/$year2',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/election/$year': typeof AppElectionYearRoute
  '/compare/$year1/$year2': typeof AppCompareYear1Year2Route
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/election/$year': typeof AppElectionYearRoute
  '/compare/$year1/$year2': typeof AppCompareYear1Year2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/election/$year': typeof AppElectionYearRoute
  '/_app/compare/$year1/$year2': typeof AppCompareYear1Year2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/election/$year' | '/compare/$year1/$year2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/election/$year' | '/compare/$year1/$year2'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/election/$year'
    | '/_app/compare/$year1/$year2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/election/$year': {
      id: '/_app/election/$year'
      path: '/election/$year'
      fullPath: '/election/$year'
      preLoaderRoute: typeof AppElectionYearRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare/$year1/$year2': {
      id: '/_app/compare/$year1/$year2'
      path: '/compare/$year1/$year2'
      fullPath: '/compare/$year1/$year2'
      preLoaderRoute: typeof AppCompareYear1Year2RouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppElectionYearRoute: typeof AppElectionYearRoute
  AppCompareYear1Year2Route: typeof AppCompareYear1Year2Route
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppElectionYearRoute: AppElectionYearRoute,
  AppCompareYear1Year2Route: AppCompareYear1Year2Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
